### ISSUE TITLE
Specify naming policy for CSS attributes (hover, disabled etc..)

### ISSUE THREAD

**Issue by niant** [niant/once#23]

**Comment by rapitkan** [comment]
Example: .hover-bgc-c:hover { background-color: map-get($colors, c); }

**Comment by niant** [comment]
Currently it's .f-[color]-hover {} or .bg-[color]-disabled {} ..I like the action before attributes in name, because all the Once classes use that (f- being font, or O -overflow.. etc..) attribute is just a modifier (hover, disabled...)

**Comment by niant** [comment]
Related https://github.com/niant/once/pull/28
